/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminStudioRouteImport } from './routes/admin.studio'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiStudioTripsRouteImport } from './routes/api/studio/trips'
import { Route as ApiStudioImagesRouteImport } from './routes/api/studio/images'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiStudioTripsRoute = ApiStudioTripsRouteImport.update({
  id: '/api/studio/trips',
  path: '/api/studio/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioImagesRoute = ApiStudioImagesRouteImport.update({
  id: '/api/studio/images',
  path: '/api/studio/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/stories': typeof StoriesRouteWithChildren
  '/studio': typeof StudioRoute
  '/timeline': typeof TimelineRoute
  '/tips': typeof TipsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/studio': typeof AdminStudioRoute
  '/api/health': typeof ApiHealthRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/studio/images': typeof ApiStudioImagesRoute
  '/api/studio/trips': typeof ApiStudioTripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/stories': typeof StoriesRouteWithChildren
  '/studio': typeof StudioRoute
  '/timeline': typeof TimelineRoute
  '/tips': typeof TipsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/studio': typeof AdminStudioRoute
  '/api/health': typeof ApiHealthRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/studio/images': typeof ApiStudioImagesRoute
  '/api/studio/trips': typeof ApiStudioTripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/stories': typeof StoriesRouteWithChildren
  '/studio': typeof StudioRoute
  '/timeline': typeof TimelineRoute
  '/tips': typeof TipsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/studio': typeof AdminStudioRoute
  '/api/health': typeof ApiHealthRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/studio/images': typeof ApiStudioImagesRoute
  '/api/studio/trips': typeof ApiStudioTripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/stories'
    | '/studio'
    | '/timeline'
    | '/tips'
    | '/admin/login'
    | '/admin/studio'
    | '/api/health'
    | '/stories/$slug'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/studio/images'
    | '/api/studio/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/stories'
    | '/studio'
    | '/timeline'
    | '/tips'
    | '/admin/login'
    | '/admin/studio'
    | '/api/health'
    | '/stories/$slug'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/studio/images'
    | '/api/studio/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/stories'
    | '/studio'
    | '/timeline'
    | '/tips'
    | '/admin/login'
    | '/admin/studio'
    | '/api/health'
    | '/stories/$slug'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/studio/images'
    | '/api/studio/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  StudioRoute: typeof StudioRoute
  TimelineRoute: typeof TimelineRoute
  TipsRoute: typeof TipsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiStudioImagesRoute: typeof ApiStudioImagesRoute
  ApiStudioTripsRoute: typeof ApiStudioTripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/studio': {
      id: '/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/studio/trips': {
      id: '/api/studio/trips'
      path: '/api/studio/trips'
      fullPath: '/api/studio/trips'
      preLoaderRoute: typeof ApiStudioTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio/images': {
      id: '/api/studio/images'
      path: '/api/studio/images'
      fullPath: '/api/studio/images'
      preLoaderRoute: typeof ApiStudioImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminStudioRoute: typeof AdminStudioRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminStudioRoute: AdminStudioRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  StoriesRoute: StoriesRouteWithChildren,
  StudioRoute: StudioRoute,
  TimelineRoute: TimelineRoute,
  TipsRoute: TipsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiStudioImagesRoute: ApiStudioImagesRoute,
  ApiStudioTripsRoute: ApiStudioTripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
